services:

  #NODE WEB
  nodeweb-container:
    build:
      context: .
      dockerfile: docker/node-web/Dockerfile
    env_file: 
      - .env
      - .env.docker
    volumes:
      - .:/app
      - nodemodules13-volume:/app/node_modules
    depends_on:
      - postgres-container
    environment:
      POSTGRES_HOST: postgres_host
      POSTGRES_PORT: 5432
    restart: unless-stopped
    networks:
      app-network:
        aliases:
            - nodeweb_host

  #NODE COMMAND
  nodecommand-container:
    build:
      context: .
      dockerfile: docker/node-command/Dockerfile
    env_file: 
      - .env
      - .env.docker
    volumes:
      - .:/app
      - nodemodules13-volume:/app/node_modules
    depends_on:
      - postgres-container
    environment:
      POSTGRES_HOST: postgres_host
      POSTGRES_PORT: 5432
    networks:
      app-network:
        aliases:
            - nodecommand_host

  #NGINX
  nginx-container:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - nodeweb-container
    networks:
      - app-network

  #POSTGRES
  postgres-container:
    image: postgres:18
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres13-volume:/var/lib/postgresql
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      app-network:
        aliases:
          - postgres_host

networks:
  app-network:
    driver: bridge

volumes:
  postgres13-volume:
  nodemodules13-volume: